/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author gabos
 */
public class VentajaJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentajaJuego.class.getName());
    private static final int TAM = 25;
    private JButton[][] celdas = new JButton[TAM][TAM];

    /**
     * Creates new form Mapa
     */
    public VentajaJuego() {
        initComponents();
        configurarUI();
        construirMapa();
        marcarCentroConReliquia(); 
    }
private void configurarUI() {
    // tamaño visual del mapa 
    panelMapa.setLayout(new GridLayout(TAM, TAM, 1, 1));
    panelMapa.setBackground(Color.DARK_GRAY);

    // Selección por defecto
    togDefensa.setSelected(true);

    // Acción limpiar
    if (btnLimpiar != null) {
        btnLimpiar.addActionListener(e -> limpiarMapa());
    }
    }
    private void construirMapa() {
    // Crea 25x25 botones y los agrega al panel
    for (int f = 0; f < TAM; f++) {
        for (int c = 0; c < TAM; c++) {
            JButton b = new JButton();
            b.setMargin(new Insets(0,0,0,0));
            b.setFocusable(false);
            b.setBackground(Color.WHITE); 
            b.setToolTipText("("+f+","+c+")");

            final int fila = f;
            final int col  = c;

            b.addActionListener(evt -> {
                colocarSegunSeleccion(fila, col);
            });

            celdas[f][c] = b;
            panelMapa.add(b);
        }
    }
    panelMapa.revalidate();
    panelMapa.repaint();
    }
private void colocarSegunSeleccion(int f, int c) {
    JButton b = celdas[f][c];

    if (togBorrar.isSelected()) {
        // Vaciar
        b.setText("");
        b.setBackground(Color.WHITE);
        return;
    }

    if (togReliquia.isSelected()) {
        // Solo 1 reliquia: elimina otras si existen
        quitarReliquiaExistente();
        b.setText("R");
        b.setBackground(new Color(0, 170, 0)); // verde
        return;
    }

    if (togDefensa.isSelected()) {
        // Evitar pisar reliquia
        if ("R".equals(b.getText())) return;
        b.setText("B");
        b.setBackground(new Color(60, 120, 220)); // azul
        return;
    }
    if (togArmas.isSelected()) {
        // Evitar pisar reliquia
        if ("R".equals(b.getText())) return;
        b.setText("A");
        b.setBackground(new Color(220, 60, 60)); // rojo
    }
}
private void quitarReliquiaExistente() {
    for (int f = 0; f < TAM; f++) {
        for (int c = 0; c < TAM; c++) {
            if ("R".equals(celdas[f][c].getText())) {
                celdas[f][c].setText("");
                celdas[f][c].setBackground(Color.WHITE);
            }
        }
    }
}

private void marcarCentroConReliquia() {
    int centro = TAM / 2; // 12 para 25
    JButton b = celdas[centro][centro];
    b.setText("R");
    b.setBackground(new Color(0, 170, 0));
}
private void limpiarMapa() {
    for (int f = 0; f < TAM; f++) {
        for (int c = 0; c < TAM; c++) {
            celdas[f][c].setText("");
            celdas[f][c].setBackground(Color.WHITE);
        }
    }
    marcarCentroConReliquia();
}
private char getCeldaSimbolo(int f, int c) {
    String t = celdas[f][c].getText();
    if (t == null || t.isEmpty()) return '.';
    return t.charAt(0); // R, B, A
}
private void generarZombiesAleatorios() {
    for (int i = 0; i < 5; i++) {
        int fila = (int) (Math.random() * TAM);
        int col = (int) (Math.random() * TAM);

        // Solo bordes del mapa
        if (fila == 0 || fila == TAM-1 || col == 0 || col == TAM-1) {
            celdas[fila][col].setText("Z");
            celdas[fila][col].setBackground(Color.RED);
        }
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        panelControles = new javax.swing.JPanel();
        togDefensa = new javax.swing.JToggleButton();
        togBorrar = new javax.swing.JToggleButton();
        togReliquia = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JButton();
        togArmas = new javax.swing.JToggleButton();
        btnZombies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMapa.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        togDefensa.setText("Defensa");
        togDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togDefensaActionPerformed(evt);
            }
        });

        togBorrar.setText("Borrar");

        togReliquia.setText("Reliquia");
        togReliquia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togReliquiaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        togArmas.setText("Armas");
        togArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togArmasActionPerformed(evt);
            }
        });

        btnZombies.setText("Zombies");
        btnZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZombiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                        .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(togBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(togDefensa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(togReliquia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(togArmas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControlesLayout.createSequentialGroup()
                        .addGroup(panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZombies)
                            .addComponent(btnLimpiar))
                        .addGap(21, 21, 21))))
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(togDefensa)
                .addGap(18, 18, 18)
                .addComponent(togBorrar)
                .addGap(18, 18, 18)
                .addComponent(togReliquia)
                .addGap(18, 18, 18)
                .addComponent(togArmas)
                .addGap(18, 18, 18)
                .addComponent(btnZombies)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void togReliquiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togReliquiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_togReliquiaActionPerformed

    private void togDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togDefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_togDefensaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarMapa();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void togArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_togArmasActionPerformed

    private void btnZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZombiesActionPerformed
        generarZombiesAleatorios();
    }//GEN-LAST:event_btnZombiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentajaJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnZombies;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JToggleButton togArmas;
    private javax.swing.JToggleButton togBorrar;
    private javax.swing.JToggleButton togDefensa;
    private javax.swing.JToggleButton togReliquia;
    // End of variables declaration//GEN-END:variables
}
